<?php

namespace AppBundle\Repository;

/**
 * BannedWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannedWordRepository extends \Doctrine\ORM\EntityRepository
{
}
