<?php

namespace AppBundle\Repository;

use AppBundle\Utils\JSONHandler;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByTopicForAjax($topicId) {

        $query = $this->getEntityManager()->createQuery(
            "SELECT c.id, c.name, c.email , c.comment, c.createdAt
            FROM AppBundle:Comment c
            WHERE c.topic = {$topicId}
            ORDER BY c.createdAt DESC
            "
        );
        
        $res = JSONHandler::prepareJSON( $query->getResult() );
        
        return $res;
    }
    
}
