<?php

namespace AppBundle\Repository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllWithCounts() {

        $query = $this->getEntityManager()->createQuery(
            'SELECT t, count(c) AS commentsCount
            FROM AppBundle:Topic t
            LEFT JOIN AppBundle:Comment c WITH c.topic = t.id
            GROUP BY t.id
            ORDER BY t.title ASC
            '
        );

        return $query->getResult();
    }

}
