<?php

namespace AppBundle\Repository;

use AppBundle\Utils\JSONHandler;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllForAjax() {

        $query = $this->getEntityManager()->createQuery(
            'SELECT t.id, t.title, count(c) AS commentsCount
            FROM AppBundle:Topic t
            LEFT JOIN AppBundle:Comment c WITH c.topic = t.id
            GROUP BY t.id
            ORDER BY t.title ASC
            '
        );


        $res = JSONHandler::prepareJSON( $query->getResult() );

        return $res;
    }

}
